#!/usr/bin/env bash
# Configure NginX server so that /redirect_me is redirecting to another page

apt-get update
apt-get -y upgrade
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent; }' /etc/nginx/sites-available/default
service nginx restart
