#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

apt-get update
apt-get -y upgrade
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
