#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

j=1
while ((j <= 100))
do
	if ((j % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((j % 3 == 0))
	then
		echo "Fizz"
	elif ((j % 5 == 0))
	then
		echo "Buzz"
	else
		echo $j
	fi
	((j++))
done
