#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2 \t localhost" > ~/hosts.new
echo -e "8.8.8.8 \t facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
